const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const AwakeNightStaffSignoffSchema = new Schema({
  ts1Approval: { type: Boolean, default: false },
  ts2Approval: { type: Boolean, default: false },
  ts3Approval: { type: Boolean, default: false },
  ts4Approval: { type: Boolean, default: false },
  ts5Approval: { type: Boolean, default: false },
  ts6Approval: { type: Boolean, default: false },
  ts7Approval: { type: Boolean, default: false },
  ts8Approval: { type: Boolean, default: false },
  ts9Approval: { type: Boolean, default: false },
  ts10Approval: { type: Boolean, default: false },
  ts11Approval: { type: Boolean, default: false },
  ts12Approval: { type: Boolean, default: false },
  ts13Approval: { type: Boolean, default: false },
  ts14Approval: { type: Boolean, default: false },
  ts15Approval: { type: Boolean, default: false },
  ts16Approval: { type: Boolean, default: false },
  ts17Approval: { type: Boolean, default: false },
  ts18Approval: { type: Boolean, default: false },
  ts19Approval: { type: Boolean, default: false },
  ts20Approval: { type: Boolean, default: false },
  ts21Approval: { type: Boolean, default: false },
  ts22Approval: { type: Boolean, default: false },
  ts23Approval: { type: Boolean, default: false },
  ts24Approval: { type: Boolean, default: false },
  ts25Approval: { type: Boolean, default: false },
  ts26Approval: { type: Boolean, default: false },
  ts27Approval: { type: Boolean, default: false },
  ts28Approval: { type: Boolean, default: false },
  ts29Approval: { type: Boolean, default: false },
  ts30Approval: { type: Boolean, default: false },
  ts31Approval: { type: Boolean, default: false },
  ts32Approval: { type: Boolean, default: false },
  ts33Approval: { type: Boolean, default: false },
  ts34Approval: { type: Boolean, default: false },
  ts35Approval: { type: Boolean, default: false },
  ts36Approval: { type: Boolean, default: false },
  ts37Approval: { type: Boolean, default: false },
  ts38Approval: { type: Boolean, default: false },
  ts39Approval: { type: Boolean, default: false },
  ts40Approval: { type: Boolean, default: false },
  ts41Approval: { type: Boolean, default: false },
  ts42Approval: { type: Boolean, default: false },
  ts43Approval: { type: Boolean, default: false },
  ts44Approval: { type: Boolean, default: false },
  ts45Approval: { type: Boolean, default: false },
  ts46Approval: { type: Boolean, default: false },
  ts47Approval: { type: Boolean, default: false },
  ts48Approval: { type: Boolean, default: false },
  ts49Approval: { type: Boolean, default: false },
  ts50Approval: { type: Boolean, default: false },

  ts1YouthStatus: { type: String, required: false },
  ts2YouthStatus: { type: String, required: false },
  ts3YouthStatus: { type: String, required: false },
  ts4YouthStatus: { type: String, required: false },
  ts5YouthStatus: { type: String, required: false },
  ts6YouthStatus: { type: String, required: false },
  ts7YouthStatus: { type: String, required: false },
  ts8YouthStatus: { type: String, required: false },
  ts9YouthStatus: { type: String, required: false },
  ts10YouthStatus: { type: String, required: false },
  ts11YouthStatus: { type: String, required: false },
  ts12YouthStatus: { type: String, required: false },
  ts13YouthStatus: { type: String, required: false },
  ts14YouthStatus: { type: String, required: false },
  ts15YouthStatus: { type: String, required: false },
  ts16YouthStatus: { type: String, required: false },
  ts17YouthStatus: { type: String, required: false },
  ts18YouthStatus: { type: String, required: false },
  ts19YouthStatus: { type: String, required: false },
  ts20YouthStatus: { type: String, required: false },
  ts21YouthStatus: { type: String, required: false },
  ts22YouthStatus: { type: String, required: false },
  ts23YouthStatus: { type: String, required: false },
  ts24YouthStatus: { type: String, required: false },
  ts25YouthStatus: { type: String, required: false },
  ts26YouthStatus: { type: String, required: false },
  ts27YouthStatus: { type: String, required: false },
  ts28YouthStatus: { type: String, required: false },
  ts29YouthStatus: { type: String, required: false },
  ts30YouthStatus: { type: String, required: false },
  ts31YouthStatus: { type: String, required: false },
  ts32YouthStatus: { type: String, required: false },
  ts33YouthStatus: { type: String, required: false },
  ts34YouthStatus: { type: String, required: false },
  ts35YouthStatus: { type: String, required: false },
  ts36YouthStatus: { type: String, required: false },
  ts37YouthStatus: { type: String, required: false },
  ts38YouthStatus: { type: String, required: false },
  ts39YouthStatus: { type: String, required: false },
  ts40YouthStatus: { type: String, required: false },
  ts41YouthStatus: { type: String, required: false },
  ts42YouthStatus: { type: String, required: false },
  ts43YouthStatus: { type: String, required: false },
  ts44YouthStatus: { type: String, required: false },
  ts45YouthStatus: { type: String, required: false },
  ts46YouthStatus: { type: String, required: false },
  ts47YouthStatus: { type: String, required: false },
  ts48YouthStatus: { type: String, required: false },
  ts49YouthStatus: { type: String, required: false },
  ts50YouthStatus: { type: String, required: false },
  createdBy: {
    type: String,
    required: false,
  },
  createdByName: {
    type: String,
    required: false,
  },
  lastEditDate: {
    type: Date,
    default: new Date(),
  },
  formType: {
    type: String,
  },
  homeId: {
    type: String,
  },
  approved: {
    type: Boolean,
    default: false,
  },
  approvedBy: {
    type: String,
    required: false,
  },
  approvedByName: {
    type: String,
    required: false,
  },
  approvedByDate: {
    type: Date,
  },
  approvedSig: {
    type: Array,
  },
  createDate: {
    type: Date,
  },
  status: {
    type: String,
  },
});

module.exports = AwakeNightStaffSignoff = mongoose.model(
  "awakeNightStaffSignoff",
  AwakeNightStaffSignoffSchema
);
